# HTTP Status Codes
RESP_OK = 200
RESP_CREATED = 201
RESP_BAD_REQUEST = 400
RESP_UNAUTHORIZED = 401
RESP_FORBIDDEN = 403
RESP_NOT_FOUND = 404
RESP_CONFLICT = 409
RESP_UNPROCESSABLE_ENTITY = 422
RESP_INTERNAL_SERVER_ERROR = 500
RESP_SERVICE_UNAVAILABLE = 503

# Error Types
BUSINESS_ERROR = "BUSINESS_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
NOT_FOUND_ERROR = "NOT_FOUND_ERROR"
CONFLICT_ERROR = "CONFLICT_ERROR"
SERVER_ERROR = "SERVER_ERROR"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

# Business Error Codes
INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
INVENTORY_NOT_FOUND = "INVENTORY_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
STORE_NOT_FOUND = "STORE_NOT_FOUND"
RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
RESERVATION_EXPIRED = "RESERVATION_EXPIRED"
RESERVATION_ALREADY_CONFIRMED = "RESERVATION_ALREADY_CONFIRMED"
OPTIMISTIC_LOCK_CONFLICT = "OPTIMISTIC_LOCK_CONFLICT"
DISTRIBUTED_LOCK_FAILED = "DISTRIBUTED_LOCK_FAILED"
INVALID_RESERVATION_STATUS = "INVALID_RESERVATION_STATUS"
